### ISSUE TITLE
Live demo is broken

### ISSUE THREAD

**Issue by ngfgrant** [clerkinc/organizations-demo#5]
When trying to access the live demo I can only see a white empty page.

Inspecting the console gives some errors. Looks to CORS related.

<img width="1440" alt="Screenshot 2022-07-14 at 11 10 24" src="https://user-images.githubusercontent.com/6362273/178958945-e7c63e66-544a-4797-a4ae-26ceaf8f3aa5.png">

**Comment by chemalopezp** [comment]
@ngfgrant it seems the URL on the repo needs to be updated, there's a different one on the README file that does work
https://organizations-demo.clerk.app/

**Comment by devchampian** [comment]
Thanks for that @chemalopezp! The live demo URL has been updated.
